### ISSUE TITLE
Raspbian Addons 帮助文档代码块显示问题

### ISSUE THREAD

**Issue by hmsjy2017** [sjtug/portal#74]
![876B3944-5E8A-4CA0-925B-F5F953DBE6F9](https://user-images.githubusercontent.com/42692274/122075885-fb9a2c00-ce2c-11eb-8b35-815ef8fbdafb.png)
![FAA95B71-9471-4896-9471-E494F23F477C](https://user-images.githubusercontent.com/42692274/122075896-fe951c80-ce2c-11eb-94e6-9099cf5e3506.jpeg)
本应以代码块的形式显示，却显示为行内代码。
https://github.com/sjtug/portal/blob/master/content/post/mirror-help/raspbian-addons.md

**Comment by skyzh** [comment]
应该给 hugo 升个级就好了，我晚点看看

**Comment by skyzh** [comment]
Well, travis-ci.org 的 build 已经停止了，我们可能要花点时间迁移到其他平台（

**Comment by hmsjy2017** [comment]
@skyzh可以用 GitHub Actions

**Comment by skyzh** [comment]
deploy key 我手里没有，过几天才能要到（

**Comment by hmsjy2017** [comment]
已解决
